apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascrib-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ascrib-app
  template:
    metadata:
      labels:
        app: ascrib-app
    spec:
      containers:
        - name: ascrib-app
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 3000
